### ISSUE TITLE
Bot UI - make zoom levels human readable

### ISSUE THREAD

**Issue by ELynx** [Tukes/GeoBot#2]
Replace zoom levels 14 15 and so on with human readable labels
Experimental:
zoom 18 = radius ~150 m
17 ~300 m
16 ~700 m
15 ~1.2 km
14 ~5 km

**Comment by Tukes** [comment]
zoom 18 не стал делать, т.к. он фактически бесполезен. Даже 17 уже слишком близко. А делать 13 и меньше грозит превышением лимита в 2048.

**Comment by Tukes** [comment]
Done. Waiting to merge.

**Comment by ELynx** [comment]
Merged to master branch
